### ISSUE TITLE
Where can I find example parameters for some of these modules?

### ISSUE THREAD

**Issue by upenr** [ansible-collections/ibm.spectrum_virtualize#11]
Where can I find example parameters for ibm_svc_volume_clone, ibm_svc_volume_snapshot, ibm_svc_volume_fcconsistgrp?

**Comment by talorh** [comment]
Hi,

From what I found there are two ways to find this out:

1) Look in plugins/modules/<module>.py and you can see some examples
2) It's documented on Ansible Automation Hub if you have a Red Hat Subscription (https://cloud.redhat.com/ansible/automation-hub/ibm/spectrum_virtualize/docs)

There may documentation elsewhere, but the above is what worked for me.

Hope this  helps.

**Comment by rohitk-github** [comment]
Thanks @talorh. Closing the issue.
