### ISSUE TITLE
Documentation of Spectrum Virtualize Rest API restrictions

### ISSUE THREAD

**Issue by fincherjc** [ansible-collections/ibm.spectrum_virtualize#2]
The Ansible modules rely on the Spectrum Virtualize Rest API to function. There isn't any reference to the Rest API restrictions on our ansible galaxy pages or in github. 

According to IBM Configuration Limits and Restrictions page the Rest API says that listing more than 2000 objects may experience a loss of service, from the API, as it restarts due to memory constraints. Also it is not possible to access the Rest API using a cluster's IPv6 address.

https://www.ibm.com/support/pages/node/744461

If we come to the ansible module page or this github there is no mention of any limitations. Could we perhaps include a reference to check the configuration limits/restrictions page for any limitations to the Rest API that might impact the use of these modules?

Admittedly the main page of ansible galaxy refers to knowledge center to learn more about the products, but nothing in there mentions the Rest API limitations.

**Comment by wangpww** [comment]
Yes, thank you very much for your suggestion, I think we need to add it. I will discuss it with the team to decide which doc we want to include this limitation.

**Comment by wangpww** [comment]
Done
