### ISSUE TITLE
MANIFEST.json missing in release 1.2.0

### ISSUE THREAD

**Issue by opokam** [ansible-collections/ibm.spectrum_virtualize#20]
##### SUMMARY
While installing from release file 1.2.0 I receive an error about a missing MANIFEST.json file:
ERROR! Collection at 'ibm.spectrum_virtualize-1.2.0.tar.gz' does not contain the required file MANIFEST.json.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy collection install ibm.spectrum_virtualize-1.2.0.tar.gz -p /opt/freeware/share/ansible/collections

##### ANSIBLE VERSION

```paste below
2.9.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AIX 7.2

##### STEPS TO REPRODUCE

Install from release file 1.2.0:
ansible-galaxy collection install ibm.spectrum_virtualize-1.2.0.tar.gz -p /opt/freeware/share/ansible/collections

```yaml

```

##### EXPECTED RESULTS

The package should install without error.

##### ACTUAL RESULTS

```paste below
ansible-galaxy collection install ibm.spectrum_virtualize-1.2.0.tar.gz -p /opt/freeware/share/ansible/collections
[WARNING]: The specified collections path '/opt/freeware/share/ansible/collections' is not part of the configured Ansible collections paths
'/root/.ansible/collections:/usr/share/ansible/collections'. The installed collection won't be picked up in an Ansible run.
Process install dependency map
ERROR! Collection at 'ibm.spectrum_virtualize-1.2.0.tar.gz' does not contain the required file MANIFEST.json.

```

**Comment by rohitk-github** [comment]
Hi @opokam "ibm.spectrum_virtualize-1.2.0.tar.gz" [https://github.com/ansible-collections/ibm.spectrum_virtualize/archive/1.2.0.tar.gz] is essentially the source code in compressed form and not the build. 
Same is valid for previous releases.

To install the IBM Spectrum Virtualize collection hosted in Galaxy:
ansible-galaxy collection install ibm.spectrum_virtualize

To upgrade to the latest version of the IBM Spectrum Virtualize collection:
ansible-galaxy collection install ibm.spectrum_virtualize --force

**Comment by opokam** [comment]
How do you install without an internet connection?

**Comment by freedge** [comment]
You have a "Download tarball" link in Galaxy that links (as we speak) to

https://galaxy.ansible.com/download/ibm-spectrum_virtualize-1.2.0.tar.gz

You can then install using the command you suggest.

**Comment by rohitk-github** [comment]
Thanks @freedge. 
@opokam I hope this answers your question.

**Comment by opokam** [comment]
Yes, thanks!
