### ISSUE TITLE
Gather all stats fails running lsnvmefabric on 8.1.3.5

### ISSUE THREAD

**Issue by robinsg** [ansible-collections/ibm.spectrum_virtualize#3]
##### SUMMARY
Using the gather info from storage example fails on V7000 running c8.1.3.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm_svc_info when specifying gather_subset: all

##### ANSIBLE VERSION
ansible 2.9.7
  config file = /home/robinsg/ansible/ibmstorage/ansible.cfg
  configured module search path = [u'/home/robinsg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

##### CONFIGURATION
DEFAULT_HOST_LIST(/home/robinsg/ansible/ibmstorage/ansible.cfg) = [u'/home/robinsg/ansible/ibmstorage/staging']

##### OS / ENVIRONMENT
V7000 running v8.1.3.5

##### STEPS TO REPRODUCE
Create a playbook file using the example on the github page.
---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
  tasks:
    - name: Gather info from storage
      ibm_svc_info:
        clustername: 172.16.x.x
        domain:
        username: superuser
        password: xxxxxxxxxxxxxxxxx
        log_path: /tmp/playbook.debug
        name: gather_info
        state: info
        gather_subset: all

When running the playbook some data is gathered but the playbook fails with:

fatal: [localhost]: FAILED! => {"changed": false, "msg": {"code": 404, "data": null, "err": ["HTTPError %s", "HTTP Error 404: Not Found"], "out": "\"Command 'lsnvmefabric' does not exist\"", "url": "https://172.16.x:x7443/rest/lsnvmefabric"}}

##### EXPECTED RESULTS
Minimum Spectrum Virtualize level for the ansible collection is 8.1.3. The lsnvmefabric command should no be executed.

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "clustername": "172.16.x.x",
            "domain": null,
            "gather_subset": [
                "all"
            ],
            "log_path": "/tmp/playbook.debug",
            "name": "gather_info",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "info",
            "username": "superuser",
            "validate_certs": false
        }
    },
    "msg": {
        "code": 404,
        "data": null,
        "err": [
            "HTTPError %s",
            "HTTP Error 404: Not Found"
        ],
        "out": "\"Command 'lsnvmefabric' does not exist\"",
        "url": "https://172.16.x.x:7443/rest/lsnvmefabric"
    }
}

**Comment by wangpww** [comment]
I think we need to remove lsnvmefabric from gather info module since from the https://www.ibm.com/support/knowledgecenter/STHLEK_8.3.0/spectrum.virtualize.cloud.830.doc/rest_api_overview.html It is not supported by the rest api. I will fix it soon

**Comment by wangpww** [comment]
Done
