### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains sanity/ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ibm.spectrum_virtualize#37]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If everything is OK, feel free to close the issue

**Comment by rohitk-github** [comment]
Which situation would require sanity/ignore-2.12.txt ?

**Comment by Andersson007** [comment]
@rohitk-github hi, thanks for the response!

1) if you already have `tests/sanity/ignore-2.11.txt` which had been used with sanity tests against the `devel` ansible-core branch before the stable-2.11 mentioned in the issue comment was created, we should copy ignore-2.11.txt to ignore-2.12.txt now, so that it will be used with the `devel` branch.
ignore-*.txt's contain sanity errors which should be intentionally ignored by the sanity tests.

I'm handling ~80 collections now, so this issue is a product of copy-past and if it's not applicable to the collection (e.g. if you don't use ignore*.txt files), feel free to ignore.

2) Also we have to be sure that the collections are tested against all the supported ansible-core versions. 2.11 is one of them. So, if it's currently tested, feel free to close the issue.

Thanks!
