### ISSUE TITLE
Invalid collection metadata. The 'license' and 'license_file' keys are mutually exclusive

### ISSUE THREAD

**Issue by thedoubl3j** [ansible-collections/ibm.spectrum_virtualize#4]
##### SUMMARY

The collection cannot have a license file present and a value to the key `license`. You can fix this by picking either the file or an entry on galaxy.yml
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

galaxy.yml

##### OS / ENVIRONMENT

f31

**Comment by wangpww** [comment]
@thedoubl3j  Thanks Jake, I have removed the value for license_file in develop branch.

**Comment by thedoubl3j** [comment]
awesome, cheers!
