### ISSUE TITLE
Usage - ibm_svc_auth

### ISSUE THREAD

**Issue by robinsg** [ansible-collections/ibm.spectrum_virtualize#67]
I'm not clear on how we use this module in Ansible.

I understand that we need to generate an authorisation token when using the APIs with https REST requests. Once we have the token it use used in subsequent https REST requests.

In the Ansible examples it looks like you request a token and then use it in subsequent requests as well as using username and password.

Can you clarify exactly how I should be using this module?

Thanks a lot.

**Comment by Shilpi-J** [comment]
@robinsg Yes, this module generates the authentication token. The output of this module (which is auth token) can be stored in a variable and that can be passed to subsequent tasks in the same playbook.
The sample playbook which depicts this module usage is available in https://github.com/ansible-collections/ibm.spectrum_virtualize/blob/develop/playbooks/

You can look for these playbooks in the above folder which uses ibm_svc_auth module to fetch the authentication token for using APIs with REST request. 
create_GMCV_in_CG.yml, volume_migrate.yml or initial_setup_system_complete.yml

**Comment by robinsg** [comment]
Thank you for this. I understand this now and will be converting my playbooks to use the auth key.

**Comment by Shilpi-J** [comment]
You are welcome, closing this issue.
