### ISSUE TITLE
Make SV documentation on Ansible Galaxy

### ISSUE THREAD

**Issue by robinsg** [ansible-collections/ibm.spectrum_virtualize#68]
I use the Ansible Galaxy website to access the IBM collections I use, e.g.  ibm.power_aix and ibm.power_ibmi. When I click on the Docs icon it takes me to the collection documentation on GitHub.io, e.g. https://ibm.github.io/ansible-for-i/index.html

When I click on the Docs icon for the ibm.spectrum_virtualize collection it takes me to the GitHub repo rather than to documentation.

To get the collection documentation I have to go to console.redhat.com.

Can you make the documentation available on GitHub.io in line with the other IBM Ansible Galaxy collections?

**Comment by Shilpi-J** [comment]
@robinsg IBM SV Ansible collection is certified by RedHat and the documentation is available on RedHat site as you also mentioned.
To make the documentation available on Ansible Galaxy, the work is under progress and the collection is under review by the galaxy team.
