### ISSUE TITLE
couldn't resolve module/action 'ibm_svc_info'

### ISSUE THREAD

**Issue by ICE-Sysadmin** [ansible-collections/ibm.spectrum_virtualize#74]
##### SUMMARY
Even if the module is installed, it seems not able to recognize it

ERROR! couldn't resolve module/action 'ibm_svc_info'. This often indicates a misspelling, missing collection, or incorrect module path.

See installation:

# ansible-galaxy collection install ibm.spectrum_virtualize --force
Process install dependency map
Starting collection install process
Installing 'ibm.spectrum_virtualize:1.10.0' to '/root/.ansible/collections/ansible_collections/ibm/spectrum_virtualize'

FIle are present in '/root/.ansible/collections/ansible_collections

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ibm.spectrum_virtualize

##### ANSIBLE VERSION

```paste below
ansible 2.9.23
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3.8
```

##### OS / ENVIRONMENT

Linux automation 5.10.135-122.509.amzn2.x86_64

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sanjaikumaar** [comment]
Hi,

If you are getting this error while installing the module, please share the complete error output and the steps you followed.

In case, if you are getting this error while running a playbook. Can you please share the playbook from which you are getting this error ?

Also, please share the output of `ansible --version` command.

**Comment by Shilpi-J** [comment]
@ICE-Sysadmin Are you still facing the issue? If yes, please share the answers of the query asked above so that we can help you.

**Comment by Shilpi-J** [comment]
Closing the issue as no further inputs are received. Please feel free to contact us in case of any issue.
