### ISSUE TITLE
Add storaage event log model

### ISSUE THREAD

**Issue by hohomeow** [ansible-collections/ibm.spectrum_virtualize#83]
Hi Team,

My customer has more than 60+ storwize storage, like V5K/V7K/FS9K/SVC.

I am testing the ansible data collection function and trying to do some automation process to reduce the team workload.

The storage data collection is cool, we already got some useful data, I would like to request to add one more feature to collect the storage logs. So customer can use ansible to quick collect the error message from storage and intergate with SNOW ticket system.

Storage command is lseventlog, detail refer to below link:
https://www.ibm.com/docs/en/flashsystem-9x00/8.4.x?topic=STSLR9_8.4.0/com.ibm.fs9200_840.doc/svc_lseventlog.html

Would you help to develop a new model for this data collection?

**Comment by Shilpi-J** [comment]
@hohomeow Thanks for the feedback.
We are including this command in our next release planned in March. I hope that will be fine.

**Comment by Shilpi-J** [comment]
The command is added in release 1.12.0
Closing the case. Feel free to open it again in case it is not working as per expectation. Thanks
