### ISSUE TITLE
Generate HTML API modules documentation on a public Website

### ISSUE THREAD

**Issue by GMLudo** [ansible-collections/ibm.spectrum_virtualize#91]
##### SUMMARY

The documentation of all modules is available with **ansible-doc** command or on:
https://console.redhat.com/ansible/automation-hub/repo/published/ibm/spectrum_virtualize/docs/

Nevertheless, the other IBM Ansible collections like Power have a public website to check the documentation directly online.
For example, with VIOS: https://ibm.github.io/ansible-power-vios/modules.html

Maybe, it might be possible to reuse this makefile:
https://github.com/IBM/ansible-power-vios/blob/dev-collection/docs/Makefile

Could you be interested in a pull request to add this support?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
all

##### ANSIBLE VERSION
```paste below
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/lg/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True

```

**Comment by Shilpi-J** [comment]
@GMLudo The documentation of IBM SV collection is also available at: https://docs.ansible.com/ansible/latest/collections/ibm/spectrum_virtualize/index.html#plugins-in-ibm-spectrum-virtualize

Do let us know if that works for you.

**Comment by Shilpi-J** [comment]
Closing this. In case you still have any issue, do let us know.

**Comment by ludovic-gasc** [comment]
Thank you @Shilpi-J for the tip.

I have just made a pull request to add this link in the README.md, feel free to change: #96
