### ISSUE TITLE
more options for ibm_svc_vdisk

### ISSUE THREAD

**Issue by scheurer13** [ansible-collections/ibm.spectrum_virtualize#97]
It would be nice if the module becomes more options.
On my case we create vdisks with ex. : "warning: 98" and "sync_rate: 95%".

https://www.ibm.com/docs/en/sanvolumecontroller/8.4.x?topic=commands-mkvdisk

Can you please implement the options equal on CLI?

**Comment by Shilpi-J** [comment]
@scheurer13 ibm_svc_vdisk module has been deprecated. We recommend to use ibm_svc_manage_volume instead.

**Comment by Shilpi-J** [comment]
Closing this
@scheurer13 feel free to re-open this in case you still have any queries.
