### ISSUE TITLE
All choices provided in ibm_svc_info.py module are not working

### ISSUE THREAD

**Issue by demahaj11** [ansible-collections/ibm.spectrum_virtualize#98]
##### SUMMARY
All choices provided in ibm_svc_info.py module are not working
Only following listed choices are getting displayed
        "Array": [],
        "FCConnectivitie": [],
        "FCConsistgrp": [],
        "FCMap": [],
        "FCPort": [],
        "Host": [],
        "HostCluster": [],
        "HostVdiskMap": [],
        "IOGroup": [],
        "Node": [],
        "Pool": [],
        "RCConsistgrp": [],
        "RemoteCopy": [],
        "System": [],
        "TargetPortFC": [],
        "VdiskCopy": [],
        "VdiskHostMap": [],
        "Volume": [],
        "changed": false,
        "failed": false,
        "iSCSIPort": []

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
/[plugins](https://github.com/ansible-collections/ibm.spectrum_virtualize/tree/develop/plugins)/[modules](https://github.com/ansible-collections/ibm.spectrum_virtualize/tree/develop/plugins/modules)
/ibm_svc_info.py

##### ANSIBLE VERSION
ansible [core 2.11.12]
  config file = /home/ansible/ansible/ansible.cfg
  configured module search path = ['/my/other/path', '/home/ansible/ansible']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jul 21 2022, 06:31:41) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 3.1.2
  libyaml = True

##### COLLECTION VERSION
└──╼ansible-galaxy collection list ibm.spectrum_virtualize

# /root/.ansible/collections/ansible_collections
Collection              Version
----------------------- -------
ibm.spectrum_virtualize 1.11.0

##### CONFIGURATION
└──╼ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/ansible/ansible/ansible.cfg) = ['/home/ansible/ansible/hosts']
DEFAULT_LOG_PATH(/home/ansible/ansible/ansible.cfg) = /home/ansible/ansible/ansible_log.txt
DEFAULT_MODULE_PATH(/home/ansible/ansible/ansible.cfg) = ['/my/other/path', '/home/ansible/ansible']
DEFAULT_MODULE_UTILS_PATH(/home/ansible/ansible/ansible.cfg) = ['/my/other/path/utils', '/home/ansible/ansible/utils']
DEFAULT_TRANSPORT(/home/ansible/ansible/ansible.cfg) = paramiko
INTERPRETER_PYTHON(/home/ansible/ansible/ansible.cfg) = python

##### OS / ENVIRONMENT
└──╼cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

##### STEPS TO REPRODUCE
    - name: Get deatils of the cluster.
      register: getinfo
      ibm.spectrum_virtualize.ibm_svc_info:
        clustername: "{{ cluster_ip }}"
        token: "{{ svc_token.token }}"
        gather_subset: [dnsserver]
        log_path: /tmp/getinfo.debug

Only working for list given above

##### EXPECTED RESULTS
svcinfo module should work for all choice provided

**Comment by sumitguptaibm** [comment]
Update:
I tested it a few times in below env.
Ansible: 2.12.0
Python: 3.9.5
ibm.spectrum_virtualize: 1.12.0

All the choices seem to work.
One such example output is:


PLAY [Using Spectrum Virtualize collection to migrate given volume] ************



TASK [Fetch authorization token for source] ************************************

ok: [localhost]



TASK [Get details of the cluster.] *********************************************

ok: [localhost]



TASK [debug] *******************************************************************

ok: [localhost] => {

    "msg": {

        "Array": [],

        "CallHome": [],

        "CloudAccount": [],

        "CloudAccountUsage": [],

        "CloudBackup": [],

        "CloudBackupGeneration": [],

        "CloudImportCandidate": [],

        "DnsServer": [],

        "Drive": [],

        "EmailServer": [],

        "EmailUser": [],

        "EventLog": [],

        "FCConnectivitie": [],

        "FCConsistgrp": [],

        "FCMap": [],

        "FCPort": [],

        "Host": [],

        "HostCluster": [],

        "HostVdiskMap": [],

        "IOGroup": [],

        "IP": [],

        "LdapServer": [],

        "Mdisk": [],

        "Node": [],

        "Ownershipgroup": [],

        "Partnership": [],

        "Pool": [],

        "Portset": [],

        "ProvisioningPolicy": [],

        "RCConsistgrp": [],

        "RemoteCopy": [],

        "ReplicationPolicy": [],

        "SafeguardedPolicy": [],

        "SafeguardedSchedule": [],

        "SnapshotPolicy": [],

        "SnapshotSchedule": [],

        "Sra": [],

        "SysLogServer": [],

        "System": [],

        "SystemCert": [],

        "TargetPortFC": [],

        "TrustStore": [],

        "User": [

            {

                "id": "0",

                "locked": "no",

                "name": "superuser",

                "owner_id": "",

                "owner_name": "",

                "password": "yes",

                "password_change_required": "no",

                "remote": "no",

                "ssh_key": "no",

                "usergrp_id": "0",

                "usergrp_name": "SecurityAdmin"

            }

        ],

        "UserGrp": [],

        "VdiskCopy": [],

        "VdiskHostMap": [],

        "Volume": [],

        "VolumeGroup": [],

        "VolumeGroupSnapshot": [],

        "VolumeGroupSnapshotPolicy": [],

        "VolumeSnapshot": [],

        "changed": false,

        "failed": false,

        "iSCSIPort": []

    }

}



PLAY RECAP *********************************************************************

localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
======================
When run directly on target:
[15:37:49] SV1_01:~ # lsuser    

id name      password ssh_key remote usergrp_id usergrp_name  owner_id owner_name locked password_change_required 

0  superuser yes      no      no     0          SecurityAdmin                     no     no                       

=================================

You may want to update the version and try it.

**Comment by sumitguptaibm** [comment]
It works perfectly with all the options.
One point to note here is, that sending a parameter "all" to get all the information may fail sometimes with error 429 ("too many requests"). The reason behind this is the huge amount of output (in one case on test nodes, it is around 188 KB) or server is too busy. The error is expected. Based on usability of the option "all", certain rate-limiting configurations, and data-compression/decompression techniques may be applied in future. For now, I'd consider it an intermittent error. Work-around is to call specific options to get related data.

If there is nothing else from you side, please close the defect.

**Comment by demahaj11** [comment]
@sumitguptaibm Thanks for the update

Tried generating output for following options and those are working fine.
system
Dnsserver
Emailserver
Emailuser
"User": [],
"UserGrp": [],

Just all option is throwing error 429 ("too many requests"). As explained above expecting fix on this in future, but as of now we have a workaround. Closing this issue. Thanks
